[book]
authors = ["Mike Maley"]
language = "en"
src = "src"

[output.html]
additional-css = ["style.css"]
edit-url-template = "https://github.com/mikem8891/learn-fea/edit/main/{path}"
git-repository-url = "https://github.com/mikem8891/learn-fea"
